baseURL = "https://hankmew.com/"
publishdir = "../docs"
themesDir = "../"
theme = "next"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true
summaryLength = 100
paginate =  5
disableKinds = ["RSS", "sitemap"]
[params]
  title = "搬砖手账"
  subtitle = "沉心营浮世，热血饮凉冰"
  author = "汉克喵"
  description = ""
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1
  pre = "fa-home"
[[menu.main]]
  url = "/about"
  name = "About"
  weight = 2
  pre = "fa-user-md"
[[menu.main]]
  url = "/posts"
  name = "Archives"
  weight = 3
  pre = "fa-archive"
[[menu.main]]
  url = "/tags"
  name = "Tags"
  weight = 4
  pre = "fa-tag"
[[menu.overview]]
  url = "https://github.com/hankmew"
  name = "Github"
  weight = 1
  pre = "fa-github"
[[menu.overview]]
  url = "mailto:hankmew@gmail.com"
  name = "E-Mail"
  weight = 2
  pre = "fa-envelope"